### ISSUE TITLE
[Feat] 클라이언트에서 불러오기 로직

### ISSUE THREAD

**Issue by SANGDOLEE** [DeveloperAcademy-POSTECH/2024-MacC-M11-1Byte#15]
## Task
- [ ]  MainGoal 클라이언트에서 불러오기
- [ ]  SubGoal 클라이언트에서 불러하기
- [ ]  DetailGoal 클라이언트에서 불러오기

**Comment by SANGDOLEE** [comment]
불러오기 기능이 함수로 뺴는게 아니고, 뷰에 바로 꽂아서 보여주기 때문에 해당 이슈는 사용 및 구현되지 않았습니다.
