### ISSUE TITLE
[Feat] 온보딩 Test Flight 마무리 구현

### ISSUE THREAD

**Issue by SANGDOLEE** [DeveloperAcademy-POSTECH/2024-MacC-M11-1Byte#33]
## Task
- [x]  온보딩 텍스트 수정
- [x]  테스트 플라이트에서 9x9 View를 넣지 않으므로, FinishView에서 Dara 이미지만 보여주기 
- [x]  만다라트 설명 탭뷰에서 Lottie 대체로 들어가있던 시스템 이미지를 다라 캐릭터로 대체
- [x]  Goal 입력시, 현재글자수/남은글자수 표시 및 모든 입력은 15글자로 제한
- [x]  온보딩에서 Goal 입력할 때, 글자수 길어질 시에 자동 줄바꿈 처리

**Comment by SANGDOLEE** [comment]
완료
